repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/Riverside-Healthcare/djlint
    rev: v1.36.4
    hooks:
      - id: djlint
        args: ["--check"]
        files: '\\.html$'
